catalog:
  services: # catalog must advertise at least one service
    - id: c21ed8d1-2b32-4a88-9095-d24684e1cb79
      name: contrast-security
      description: Provide Contrast credentials to an application
      bindable: true
      tags:
        - contrast
        - security
      metadata:
        displayName: Contrast Security
        imageUrl: https://avatars2.githubusercontent.com/u/5577345?v=3&s=200
        longDescription: The service broker plans offered are user configured within Ops Manager.
        providerDisplayName: Contrast Security
        documentationUrl: https://github.com/Contrast-Security-OSS/docs
        supportUrl: https://support.contrastsecurity.com

      # these get build dynamically from the bound environment variables
      # plans: # a service has one or more plans
      #  - id: c05855e7-a55d-4ba1-b462-7579df7514f4
      #    name: public
      #    description:
      #    metadata:
      #      bullets:
      #        - Repos are public
      #      displayName: Public